### ISSUE TITLE
Distribute on RetroArch Content Downloader

### ISSUE THREAD

**Issue by RobLoach** [sgadrat/super-tilt-bro#1]
RetroArch has a content downloader which allows you to download homebrew content directly through the user interface. We love Super Tilt Bros and were wondering if we could distribute it on the Content Downloader!

It would end up being available for download from:
http://buildbot.libretro.com/assets/cores/Nintendo%20-%20Nintendo%20Entertainment%20System/

Would you be okay with this? Thanks!

**Comment by sgadrat** [comment]
It would be awesome!

Super Tilt Bro. would be honored of being in the downloads of a flagship
project like retroarch. If you just want my consent, you have it for sure.

I note that contrarily to already proposed ROMs by your download manager, Super Tilt Bro. embraces continued development. Do you want to handle updates? If so, how do you want to proceed.

If you don't want to keep an eye on minor updates, the version 1.0 is
to be released/tagged on October 27.

**Comment by sgadrat** [comment]
Super Tilt Bro. has been added to the list.

**Comment by RobLoach** [comment]
Thanks for the :+1: .... It's a great game.
