### ISSUE TITLE
Build fails with out of memory errors

### ISSUE THREAD

**Issue by Rampoina** [sgadrat/super-tilt-bro#3]
The build is failing with out of memory errors.
Tested on `master` and most recent tags

System: Arch linux
```
uname -a                                                                                                                                                                              
Linux rampoina 5.15.10-arch1-1 #1 SMP PREEMPT Fri, 17 Dec 2021 11:17:37 +0000 x86_64 GNU/Linux
```

```
xa --version                                                                                                                                                                       
xa (xa65) v2.3.12
```

```
6502-gcc --version                                                                                                                                                                  
6502-gcc (GCC) 8.4.1 20210210
Copyright (C) 2018 Free Software Foundation, Inc.
```

```
===== DATA04-BANK =====
  bne end
game/data/stages/gem/gem-logic.asm:line 488: 8d72:Out of memory error
  lda stage_gem_gem_cooldown_high
game/data/stages/gem/gem-logic.asm:line 489: 8d74:Out of memory error
  rts
game/data/stages/gem/gem-logic.asm:line 492: 8d75:Out of memory error
  lda stage_gem_gem_position_x_high
game/data/stages/gem/gem-logic.asm:line 499: 8d77:Out of memory error
  sta tmpfield1
```

[build.log](https://github.com/sgadrat/super-tilt-bro/files/7775787/build.log)

**Comment by fantastic-Mr-asshole** [comment]
For what is worth, I can also reproduce this very same issue with my old ubuntu:
```
uname -a
Linux Rachael 4.4.0-186-generic #216-Ubuntu SMP Wed Jul 1 05:34:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```

```
xa --version
xa (xa65) v2.3.5
```

```
6502-gcc --version
6502-gcc (GCC) 8.4.1 20210210
```

using tag 2.0-alpha10 but with same exact result:
```
===== DATA04-BANK =====
  bne end
game/data/stages/gem/gem-logic.asm:line 488: 8d72:Out of memory error
  lda stage_gem_gem_cooldown_high
game/data/stages/gem/gem-logic.asm:line 489: 8d74:Out of memory error
  rts
```

**Comment by sgadrat** [comment]
Oh sorry, I really should indicate it in the build instructions:

XA does not allocate enough memory to compile Super Tilt Bro. since a long time. I switched to a modified version, as it is a compile-time constant.

Here it is: https://github.com/sgadrat/xa65-stb

So, you can compile this xa version, and build with: `XA_BIN=/path/to/your/xa_dir/xa ./build.sh`

**Comment by Rampoina** [comment]
thank you very much, the build process seems to succeed now!

I can't seem to run the generated rom though.
fceux complains about

```iNES mapper #3872 is not supported at all. fceux```

and mednaffen seems to load the initial animation but hangs there

**Comment by sgadrat** [comment]
The build should output multiple files, three of them may interest you:
 * `Super_Tilt_Bro_(E).nes`: the game with Wi-Fi capability. As the physical mapper is in development, it is supported by no emulator. We have an experimental fork of FCEUX with support for it here: https://github.com/sgadrat/fceux/tree/rainbow-stable
 * `tilt_no_network_unrom_(E).nes`: the game without networking capability but compatible with most emulators (UNROM mapper)
 * `server_bytecode.nes`: actually not a valid NES ROM, but allows to build the server (here, but severly lacks documentation: https://github.com/sgadrat/super-tilt-bro-server)

**Comment by Rampoina** [comment]
I see, that makes sense.

`tilt_no_network_unrom_(E).nes` works without any issues!

thank you for your explanation and patience (and the awesome game!)

**Comment by sgadrat** [comment]
Happy that you got you out of trouble. Have fun with the game!
